version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - zip -r distributable_lambda.zip ./src
artifacts:
  files:
    - distributable_lambda.zip
  name: test-lambda-$Env:CODEBUILD_BUILD_NUMBER-$(Get-Date -UFormat "%Y%m%d-%H%M%S")
  secondary-artifacts:
    appSpec:
      files:
        - appspec.yml
      name: appspec.yml

